# Redirects configuration
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/icons/*"
to = "/icons/:splat"
status = 200
[redirects.headers]
Cache-Control = "public, max-age=604800"

[[redirects]]
from = "/favicon.ico"
to = "/icons/favicon.ico"
status = 200

[build]
functions = "functions"

[functions]
directory = "functions"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"

